name: Comment
on: [status]

jobs:
  artifact-comment:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - uses: actions/checkout@v1

      - name: Get artifact URL
        id: getArtifact
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/_build/html/index.html
          circleci-jobs: build
