name: Build QML Branch - Master
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0,2,4,6' # At 00:00 on Sunday, Tuesday, Thursday, and Saturday.


concurrency:
  group: build-qml-demo-branch-master
  cancel-in-progress: true


jobs:
  build_master:
    # Referencing the actions using the remote-call URL as we do not want to use the local copy of the called
    # workflow, but instead want to use the version of the workflow on the @master branch
    uses: PennyLaneAI/qml/.github/workflows/build-branch.yml@master
    with:
      branch: master
      num_workers: '10'
