name: Build QML Branch - Master
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0,2,4,6' # At 00:00 on Sunday, Tuesday, Thursday, and Saturday.


concurrency:
  group: build-qml-demo-branch-master
  cancel-in-progress: true


jobs:
  build_master:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: master
      num_workers: '10'
