name: V1 Deprecation Warning Check
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-directory:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.check.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for deprecated directory changes
        id: check
        run: |
          changed_files=$(git diff --name-only --diff-filter=AMR ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^demonstrations/' || true)

          if [ -n "$changed_files" ]; then
            # output success = false if changes are found
            echo "success=false" >> $GITHUB_OUTPUT
          else
            #output success = false if no changes are found
            echo "success=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: steps.check.outputs.success == 'false'
        uses: XanaduAI/cloud-actions/create-and-update-pull-request-comment@main
        with:
          github_token: ${{ secrets.github_token }}
          comment_uid: v1-deprecation-warning
          pull_request_number: ${{ github.event.pull_request.number }}
          comment_body: |
            ### ⚠️ Deprecation Warning ⚠️ 
            You are modifying files in the \`demonstrations/\` directory. This directory is no longer in use.

            Please add or move your files to \`demonstrations_v2/\`, and use the following [format](./CONTRIBUTING.md#manually-creating-a-demo):

            \`\`\`
            your_demo_name/
                - demo.py
                - metadata.json
                - requirements.in (optional)
            \`\`\`

            For additional information, please refer to the [contributing guidelines](./CONTRIBUTING.md)
