name: V2 Build Demos for SWC Environment

on:
  push:
    branches:
      - master
      - test-v2-master
      - dev
      - test-v2-dev

permissions:
  contents: read
  actions: read
  pull-requests: write

concurrency:
  group: demo-deployment-build-${{ github.sha }}
  cancel-in-progress: true

jobs:
  # Step 1: Identify changed demos
  identify-changed-demos:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.get-changed-demos.outputs.updated }}
      deleted: ${{ steps.get-changed-demos.outputs.deleted }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed demos
        id: get-changed-demos
        uses: ./.github/actions/get-changed-demos

      - name: Output changed demos
        run: |
          echo "Updated Demos: ${{ steps.get-changed-demos.outputs.updated }}"
          echo "Deleted Demos: ${{ steps.get-changed-demos.outputs.deleted }}"

  # Step 2: Build demos
  build:
    if: needs.identify-changed-demos.outputs.updated != ''
    uses: ./.github/workflows/v2-build-demos.yml
    needs:
      - identify-changed-demos
    with:
      ref: ${{ github.sha }}
      demo-names: ${{ needs.identify-changed-demos.outputs.updated }}
      dev: ${{ github.ref_name == 'dev' || github.ref_name == 'test-v2-dev' }} # TODO remove test-v2-dev when stable
      save-artifact: true
      artifact-name: demo-deployment-build-${{ github.sha }}
      keep-going: false
      quiet: false
      batch_size: 10

  # Step 3: Save build context
  save-build-context:
    if: needs.identify-changed-demos.outputs.updated != ''
    runs-on: ubuntu-latest
    needs:
      - build
      - identify-changed-demos
    steps:
      - name: Save Merge Commit Information
        run: |
          mkdir -p /tmp/merge
          cat >/tmp/merge/deployment_build_context.json <<EOL
          {
            "ref": "${{ github.sha }}",
            "ref_name": "${{ github.ref_name }}",
            "updated_demos": "${{ needs.identify-changed-demos.outputs.updated }}",
            "deleted_demos": "${{ needs.identify-changed-demos.outputs.deleted }}"
          }
          EOL

      - name: Upload Pull Request Event Context as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment_build_context
          path: /tmp/merge
          retention-days: 30
