name: V2 Deploy PR

on:
  workflow_run:
    workflows:
      - "V2 Build PR"
    types:
      - completed

permissions:
  actions: read
  pull-requests: write
  contents: read

concurrency:
  group: deploy-v2-demos-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  # Step 1: Prepare the build context
  prepare-build-context:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # Download the build context artifact
      - name: Download Build Context
        uses: XanaduAI/cloud-actions/download-github-workflow-artifact@main
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifact_name_regex: '^pr_info$'
          github_token: ${{ github.token }}

      # Check if the build context file exists
      - name: Check if Build Context file exists
        id: build_context
        env:
          context_artifact_file_name: pr_info.zip
        run: |
          if test -f "$context_artifact_file_name"; then
            echo "result=$context_artifact_file_name" >> $GITHUB_OUTPUT
          fi

      # Unpack the build information if the file exists
      - name: Unpack Build Information
        if: steps.build_context.outputs.result != ''
        run: unzip ${{ steps.build_context.outputs.result }}

      # Read the build information from the unpacked file
      - name: Read Build Information
        id: read_build_info
        if: steps.build_context.outputs.result != ''
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const buildData = fs.readFileSync('pr_info.json', 'utf8');
            return JSON.parse(buildData);

      # Parse pull request event information
      - name: Parse Pull Request Event Information
        id: pr_info
        if: github.event.workflow_run.event == 'pull_request' && steps.build_context.outputs.result != ''
        run: |
          echo '${{ steps.read_build_info.outputs.result }}' | jq -r '.id' > pr_id.txt
          echo '${{ steps.read_build_info.outputs.result }}' | jq -r '.ref' > pr_ref.txt
          echo '${{ steps.read_build_info.outputs.result }}' | jq -r '.ref_name' > pr_ref_name.txt
          echo '${{ steps.read_build_info.outputs.result }}' | jq -c '.updated_demos' > updated_demos.json
          echo '${{ steps.read_build_info.outputs.result }}' | jq -c '.deleted_demos' > deleted_demos.json

          echo "pr_id=$(cat pr_id.txt)" >> $GITHUB_OUTPUT
          echo "pr_ref=$(cat pr_ref.txt)" >> $GITHUB_OUTPUT
          echo "pr_ref_name=$(cat pr_ref_name.txt)" >> $GITHUB_OUTPUT
          echo "updated_demos=$(cat updated_demos.json)" >> $GITHUB_OUTPUT
          echo "deleted_demos=$(cat deleted_demos.json)" >> $GITHUB_OUTPUT

      # Set job outputs for downstream jobs
      - name: Set job outputs
        if: github.event.workflow_run.event == 'pull_request' && steps.build_context.outputs.result != ''
        id: set_job_outputs
        run: |
          echo "pr_id=${{ steps.pr_info.outputs.pr_id }}" >> $GITHUB_OUTPUT
          echo "pr_ref=${{ steps.pr_info.outputs.pr_ref }}" >> $GITHUB_OUTPUT
          echo "pr_ref_name=${{ steps.pr_info.outputs.pr_ref_name }}" >> $GITHUB_OUTPUT
          echo "updated_demos=${{ steps.pr_info.outputs.updated_demos }}" >> $GITHUB_OUTPUT
          echo "deleted_demos=${{ steps.pr_info.outputs.deleted_demos }}" >> $GITHUB_OUTPUT
    outputs:
      pr_id: ${{ steps.set_job_outputs.outputs.pr_id }}
      pr_ref: ${{ steps.set_job_outputs.outputs.pr_ref }}
      pr_ref_name: ${{ steps.set_job_outputs.outputs.pr_ref_name }}
      updated_demos: ${{ steps.set_job_outputs.outputs.updated_demos }}
      deleted_demos: ${{ steps.set_job_outputs.outputs.deleted_demos }}

  # Step 2: Deploy the demos to SWC
  deploy-preview-demos:
    uses: ./.github/workflows/v2-deploy-demos.yml
    needs: prepare-build-context
    if: github.event.workflow_run.event == 'pull_request' && needs.prepare-build-context.result == 'success'
    with:
      # TODO: Update SWC environment to "swc-prod"
      environment: 'swc-staging' 
      artifact-name: demo-build-${{ needs.prepare-build-context.outputs.pr_ref }}
      preview: true
      branch: ${{ needs.prepare-build-context.outputs.pr_ref_name }}
    secrets: inherit
  
  # Step 3: Generate a comment with the demo names
  generate-comment:
    runs-on: ubuntu-latest
    needs: prepare-build-context
    if: github.event.workflow_run.event == 'pull_request' && needs.prepare-build-context.outputs.pr_id != ''
    steps:
      # Generate a markdown comment with demo names
      - name: Create markdown comment from demo names
        id: generate-markdown
        run: |
          demos="demo1 demo2 demo3"
          
          comment="### Preview(s) are ready! :tada:\n"
          comment+="<details>\n"
          comment+="<summary>Toggle to view preview links</summary>\n"
          comment+="\n"

          for demo in $demos; do
            comment+="- [$demo](https://pennylane.ai/qml/demos/$demo?preview=true)\n"
          done
      
          comment+="\n"
          comment+="</details>"

          # Set the markdown as an output variable
          echo "::set-output name=markdown::$comment"

      # Post the comment on the pull request
      - name: Comment on PR
        id: comment-on-pr
        uses: XanaduAI/cloud-actions/create-and-update-pull-request-comment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ needs.prepare-build-context.outputs.pr_id }}
          comment_body: ${{ steps.generate-markdown.outputs.markdown }}
